#docker-composeバージョン
version: "3.8"

volumes:
  db-volume:
  maildir: {}

#コンテナ詳細
services:
  #メールサーバのコンテナ
  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
